L2Test/L2Test/Models/ManageViewModels.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security;

namespace L2Test.Models
{
    public class IndexViewModel
    {
        public bool HasPassword { get; set; }
        public IList<UserLoginInfo> Logins { get; set; }
        public string PhoneNumber { get; set; }
        public bool TwoFactor { get; set; }
        public bool BrowserRemembered { get; set; }
    }

    public class ManageLoginsViewModel
    {
        public IList<UserLoginInfo> CurrentLogins { get; set; }
        public IList<AuthenticationDescription> OtherLogins { get; set; }
    }

    public class FactorViewModel
    {
        public string Purpose { get; set; }
    }

    public class SetPasswordViewModel
    {
        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "New password")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm new password")]
        [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }

    public class ChangePasswordViewModel
    {
        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Current password")]
        public string OldPassword { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "New password")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm new password")]
        [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }

    public class AddPhoneNumberViewModel
    {
        [Required]
        [Phone]
        [Display(Name = "Phone Number")]
        public string Number { get; set; }
    }

    public class VerifyPhoneNumberViewModel
    {
        [Required]
        [Display(Name = "Code")]
        public string Code { get; set; }

        [Required]
        [Phone]
        [Display(Name = "Phone Number")]
        public string PhoneNumber { get; set; }
    }

    public class ConfigureTwoFactorViewModel
    {
        public string SelectedProvider { get; set; }
        public ICollection<System.Web.Mvc.SelectListItem> Providers { get; set; }
    }
}

L2Test/L2Test/Controllers/ArchiveController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace L2Test.Controllers
{
    //This controller only exists to allow me to make a longer route for the archives so that Javascript will break on the test result pages.
    public class ArchiveController : Controller
    {
        // GET: Archive
        public ActionResult Index()
        {
            return Redirect("/Home/Manage");
        }

        [HttpPost]
        [Authorize]
        public ActionResult ReportCards(string filepath)
        {
            return File(filepath, "text/html");
        }
    }
}

L2Test/L2Test/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Web;
using System.Web.Mvc;
using L2Test.Helpers;
using L2Test.Models;
using System.IO;
using Ionic.Zip;

namespace L2Test.Controllers
{
    public class HomeController : Controller
    {
        //AllowAnonymous means that users do not need to authenticate to use/see this page
        //Authorize means that users have to be logged in to view the page.

        [HttpGet]
        [AllowAnonymous] 
        public ActionResult Index() 
        {
            return RedirectToAction("Home");
        }

        [HttpGet]
        [AllowAnonymous]//Techs need to access this page to start taking the test
        public ActionResult Home()
        {
            ViewBag.HomePageText = Config.GetString("HomePage");

            if (TempData["error"] == null)
                ViewBag.Error = "";
            else
                ViewBag.Error = TempData["error"].ToString();

            return View();
        }

        [HttpPost]
        [AllowAnonymous]//Used to authenticate the techs temp ID
        public ActionResult Home(string formTechID)
        {
            return Redirect("~/Home/Test/" + formTechID);
        }

        [HttpGet]
        [AllowAnonymous]//Techs need access to this page
        public ActionResult Test()
        {
            TechModels Check = new TechModels();
            TestQuestions List = new TestQuestions();

            ViewBag.TimeToTakeTest = Config.GetInt("TimeToTakeTest");
            string URL = Request.Url.ToString();
            string TechID = Path.GetFileName(URL);

            if (Check.isValid(TechID))
                return View();

            TempData["error"] = "ERROR: Invalid ID. Please verify you entered the ID correctly. ID is only valid for 90 minutes, ask lead to create a new ID for you if your ID is not working.";
            return RedirectToAction("Home");
        }

        [HttpGet]
        [Authorize]
        public ActionResult Edit(string Error = "")
        {
            ViewBag.Err = Error;
            TestQuestions List = new TestQuestions();
            return View();
        }

        [HttpPost, ValidateInput(false)]
        [Authorize]
        public ActionResult Edit(TestEditModel jsonData)
        {
            TestEditModel help = new TestEditModel();
            help.NewQuestion(jsonData);
            return Json(new { success = true });
        }

        [HttpGet]
        [Authorize]
        public ActionResult EditQuestion()
        {
            return View();
        }

        [HttpPost, ValidateInput(false)]
        [Authorize]
        public ActionResult EditQuestion(TestEditModel jsonData)
        {
            TestEditModel Help = new TestEditModel();
            Help.EditQuestion(jsonData);
            return Json(new { success = true});
        }

        [HttpPost]
        [Authorize]
        public ActionResult UploadImage(HttpPostedFileBase file)
        {
            Image ImageHelp = new Image();
            return Json(ImageHelp.Upload(file));
        }

        [HttpPost]
        [Authorize]
        public ActionResult Delete(string uid)
        {
            EditTest.Delete(uid);
            return Redirect("~/Home/Edit");
        }

        [HttpGet]
        [Authorize]
        public ActionResult Manage()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        public ActionResult Manage(string formTechName)
        {
            TechModels tech = new TechModels();
            tech.CreateNew(formTechName);
            return View();
        }

        [HttpPost]
        [Authorize]
        public ActionResult ManageDelete(string uid)
        {
            UserMgmt.Delete(uid);
            return Redirect("~/Home/Manage");
        }

        [HttpPost]
        [Authorize]
        public ActionResult ManageEdit(string uid, string newPassword)
        {
            UserMgmt.PaswordUpdate(uid, newPassword);
            return Redirect("~/Home/Manage");
        }

        [HttpPost]
        [AllowAnonymous] //Used to submit test
        public ActionResult TestResults(IEnumerable<TestResultModel> jsonData)
        {
            GradeTest help = new GradeTest();
            return Content(help.Submit(jsonData));
        }

        [HttpPost]
        [AllowAnonymous] //Used to save snapshot of HTML at time the submit button was pressed.
        public void TestArchive(string html, string tech)
        {
            GradeTest help = new GradeTest();
            help.Archive(html, tech);
        }

        [HttpGet]
        [Authorize]
        public ActionResult ReportCards()
        {
            ReportCardHelper helper = new ReportCardHelper();
            ViewBag.GradedResults = helper.GetGradedReport(Server.MapPath(@"~\Views\Tests\Graded"));
            ViewBag.ArchiveResults = helper.GetGradedReport(Server.MapPath(@"~\Views\Tests\Ungraded"));
            return View();
        }

        [HttpGet]
        [Authorize]
        public FilePathResult Backup()
        {
            DatabaseBackup DB = new DatabaseBackup();
            string fileName = "L2Test_Backup_" + DateTime.Now.ToString("yyyy-MM-dd") + ".zip";
            DB.Backup(Server.MapPath(@"~\Content\Backup\tmp\"));

            using (ZipFile zip = new ZipFile())
            {
                zip.AddDirectory(Server.MapPath(@"~\Content\Backup\tmp\"));
                zip.AddDirectoryByName("Images");
                zip.AddDirectory(Server.MapPath(@"~\Content\Images"), "Images");
                zip.AddDirectory(Server.MapPath(@"~\Views\Tests"));
                zip.Save(Server.MapPath(@"~\Content\Backup\" + fileName));
            }
            return new FilePathResult(Server.MapPath(@"~\Content\Backup\" + fileName), "application/zip");
        }

        [HttpPost]
        [Authorize]
        public ActionResult Restore(HttpPostedFileBase file)
        {
            DatabaseBackup DB = new DatabaseBackup();
            DB.Restore(file);
            return Redirect("~/Home/Edit");
        }

        [HttpGet]
        [Authorize]
        public ActionResult About()
        {
            ViewBag.AboutPageText = Config.GetString("AboutPage");
            return View();
        }

        [HttpGet]
        [Authorize]
        public ActionResult Configuration()
        {
            ViewBag.HomePage = Config.GetString("HomePage");
            ViewBag.AboutPage = Config.GetString("AboutPage");
            ViewBag.NumberOfQuestions = Config.GetInt("NumberOfQuestions");
            ViewBag.PassingScore = Config.GetInt("PassingScore");
            ViewBag.TimeToTakeTest = Config.GetInt("TimeToTakeTest");
            ViewBag.TimeToStartTest = Config.GetInt("TimeToStartTest");
            ViewBag.Name = Config.GetString("Name");

            return View();
        }

        [HttpPost, ValidateInput(false)]
        [Authorize] 
        public ActionResult Configuration(int formQuestions = -1, int formScore = -1, int formTimeToTake = -1, int formStart = -1, string formHomePage = "", string formAboutPage = "", string formName ="")
        {
            //Get all the current values
            string HomePage = Config.GetString("HomePage");
            string AboutPage = Config.GetString("AboutPage");
            string Name = Config.GetString("Name");
            int NumberOfQuestions = Config.GetInt("NumberOfQuestions");
            int PassingScore = Config.GetInt("PassingScore");
            int TimeToTakeTest = Config.GetInt("TimeToTakeTest");
            int TimeToStartTest = Config.GetInt("TimeToStartTest");

            //Only update values if entry is valid and was changed/submitted
            if (formQuestions > 0) { NumberOfQuestions = formQuestions; }
            if (formScore > 0) { PassingScore = formScore; }
            if (formTimeToTake > 0) { TimeToTakeTest = formTimeToTake; }
            if (formStart > 0) { TimeToStartTest = formStart; }
            if (formHomePage != "") { HomePage = formHomePage; }
            if (formAboutPage != "") { AboutPage = formAboutPage; }
            if (formName != "") { Name = formName; }

            Config.Update(HomePage, AboutPage, NumberOfQuestions, PassingScore, TimeToTakeTest, TimeToStartTest, Name);

            return Redirect("~/Home/Configuration");
        }

        [ChildActionOnly]
        public ActionResult SiteName()
        {
            return new ContentResult {Content = Config.GetString("Name")};
        }
    }
}

L2Test/L2Test/Views/Home/About.cshtml

@{
    ViewBag.Title = "About";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="SubmitFloat">
    <center></center>
</div>

<!--
 _____           _           _     _         _      _____   _____         _
|  __ \         | |         | |   | |       | |    / __  \ |_   _|       | |
| |  \/ ___   __| | __ _  __| | __| |_   _  | |    `' / /'   | | ___  ___| |_
| | __ / _ \ / _` |/ _` |/ _` |/ _` | | | | | |      / /     | |/ _ \/ __| __|
| |_\ \ (_) | (_| | (_| | (_| | (_| | |_| | | |____./ /___   | |  __/\__ \ |_
 \____/\___/ \__,_|\__,_|\__,_|\__,_|\__, | \_____/\_____/   \_/\___||___/\__|
                                      __/ |
                                     |___/
-->

<article>
    @Html.Raw(ViewBag.AboutPageText)
</article>

L2Test/L2Test/Views/Home/Configuration.cshtml

@{
    ViewBag.Title = "Configuration";
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.RestoreURL = Url.Action("Restore", "Home", routeValues: null, protocol: Request.Url.Scheme);
}

<!--
 _____           _           _     _         _      _____   _____         _
|  __ \         | |         | |   | |       | |    / __  \ |_   _|       | |
| |  \/ ___   __| | __ _  __| | __| |_   _  | |    `' / /'   | | ___  ___| |_
| | __ / _ \ / _` |/ _` |/ _` |/ _` | | | | | |      / /     | |/ _ \/ __| __|
| |_\ \ (_) | (_| | (_| | (_| | (_| | |_| | | |____./ /___   | |  __/\__ \ |_
 \____/\___/ \__,_|\__,_|\__,_|\__,_|\__, | \_____/\_____/   \_/\___||___/\__|
                                      __/ |
                                     |___/
-->

<br />
<br />
<form action="" method="post" enctype="multipart/form-data" class="form-horizontal">
    <fieldset>

        <!-- Text input-->
        <div class="form-group">
            <label class="col-md-4 control-label" for="formQuestions">Number of questions on test</label>
            <div class="col-md-4">
                <input id="formQuestions" name="formQuestions" type="text" placeholder="@ViewBag.NumberOfQuestions" class="form-control input-md">

            </div>
        </div>

        <!-- Text input-->
        <div class="form-group">
            <label class="col-md-4 control-label" for="formScore">Minimum score percentage to pass</label>
            <div class="col-md-4">
                <input id="formScore" name="formScore" type="text" placeholder="@ViewBag.PassingScore" class="form-control input-md">

            </div>
        </div>

        <!-- Text input-->
        <div class="form-group">
            <label class="col-md-4 control-label" for="formTimeToTake">Time in minutes to take test</label>
            <div class="col-md-4">
                <input id="formTimeToTake" name="formTimeToTake" type="text" placeholder="@ViewBag.TimeToTakeTest" class="form-control input-md">

            </div>
        </div>

        <!-- Text input-->
        <div class="form-group">
            <label class="col-md-4 control-label" for="formStart">Time in minutes before Test ID expires</label>
            <div class="col-md-4">
                <input id="formStart" name="formStart" type="text" placeholder="@ViewBag.TimeToStartTest" class="form-control input-md">

            </div>
        </div>

        <!-- Text input-->
        <div class="form-group">
            <label class="col-md-4 control-label" for="formName">Site Name</label>
            <div class="col-md-4">
                <input id="formName" name="formName" type="text" placeholder="@ViewBag.Name" class="form-control input-md">

            </div>
        </div>

        <!-- Textarea -->
        <div class="form-group">
            <label class="col-md-4 control-label" for="formHomePage">Home Page Text</label>
            <div class="col-md-4">
                <textarea class="form-control" id="formHomePage" name="formHomePage" placeholder="@ViewBag.HomePage" rows="10"></textarea>
            </div>
        </div>

        <!-- Textarea -->
        <div class="form-group">
            <label class="col-md-4 control-label" for="formAboutPage">About Page Text</label>
            <div class="col-md-4">
                <textarea class="form-control" id="formAboutPage" name="formAboutPage" placeholder="@ViewBag.AboutPage" rows="10"></textarea>
            </div>
        </div>

        <!-- Button -->
        <div class="SubmitFloat">
            <center>
                <button id="submitButton" name="submitButton" class="btn btn-success">Submit Changes</button>
                @Html.ActionLink("Backup Website", "Backup", "Home", null, new { @class = "btn btn-info" })
                <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#restoreModal">Restore From Backup</button>
            </center>
        </div>
    </fieldset>
</form>
<div class="modal fade" id="restoreModal" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" id="editbtn" class="close" data-dismiss="modal">&times;</button>
                <h2 class="modal-title">Restore Database From Backup</h2>
                <center><p>This will reset all site settings and test questions.</p></center>
            </div>
            <div class="modal-body">
                <form action="@ViewBag.RestoreURL" method="post" enctype="multipart/form-data" class="form-horizontal">
                    <fieldset>
                        <!-- File Button -->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="file">SQL file (.BAK)</label>
                            <div class="col-md-4">
                                <input id="file" name="file" class="input-file" type="file">
                            </div>
                        </div>

                        <!-- Button (Double) -->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="Upload"></label>
                            <div class="col-md-8">
                                <button id="button1id" name="Upload" class="btn btn-success">Upload File</button>
                                <button id="cancel" name="cancel" class="btn btn-danger" data-dismiss="modal">Cancel</button>
                            </div>
                        </div>
                    </fieldset>
                </form>
</div>  <!--Modal Body-->

        </div> <!--Modal Content-->
    </div> <!--Modal Dialog-->
</div>


L2Test/L2Test/Views/Home/Edit.cshtml
@{
    ViewBag.Title = "Edit Test";
    Layout = "~/Views/Shared/_Layout.cshtml";
    L2Test.Helpers.EditTest ListHelp = new L2Test.Helpers.EditTest();
    ViewBag.ResultsURL = Url.Action("Edit", "Home", routeValues: null, protocol: Request.Url.Scheme);
    ViewBag.UploadURL = Url.Action("UploadImage", "Home", routeValues: null, protocol: Request.Url.Scheme);
}
<!--
 _____           _           _     _         _      _____   _____         _
|  __ \         | |         | |   | |       | |    / __  \ |_   _|       | |
| |  \/ ___   __| | __ _  __| | __| |_   _  | |    `' / /'   | | ___  ___| |_
| | __ / _ \ / _` |/ _` |/ _` |/ _` | | | | | |      / /     | |/ _ \/ __| __|
| |_\ \ (_) | (_| | (_| | (_| | (_| | |_| | | |____./ /___   | |  __/\__ \ |_
 \____/\___/ \__,_|\__,_|\__,_|\__,_|\__, | \_____/\_____/   \_/\___||___/\__|
                                      __/ |
                                     |___/
-->
<h1 style="color:orangered;">@ViewBag.Err</h1>

<div class="SubmitFloat">
    <center><button type="button" class="btn btn-success btn-lg" data-toggle="modal" data-target="#addModal">Add New Question</button></center>
</div>

<!--************************Add Question***************************-->
<div class="modal custom fade" id="addModal" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" id="editbtn" class="close" data-dismiss="modal">&times;</button>
                <h2 class="modal-title">Add New Question</h2>
                <center><p>Put a check mark next to all correct answers.</p></center>
            </div>
            <div class="modal-body">
                <fieldset>
                    <!-- Get Question -->
                    <div class="form-group col-md-12">
                        <label class="col-md-4 control-label" for="formQuestion">Question Text: </label>
                        ed<div class="col-md-offset-4">
                            <textarea class="form-control" id="formQuestion" name="formQuestion" maxlength="899"></textarea>
                        </div>
                        <br/>
                    </div>
                    <!-- Get Category -->
                    <div class="form-group col-md-12">
                        <label class="col-md-4 control-label" for="formCategory">Select Category:</label>
                        <div class="col-md-offset-4">
                            <select id="formCategory" name="formCategory" class="form-control">
                                <option value="1">New Categoy:</option>
                                @Html.Raw(ListHelp.CategoryList())
                            </select>
                        </div>
                    </div>
                    <!-- New Category-->
                    <div class="form-group col-md-12">
                        <label class="col-md-4 control-label" for="newCategory">New Category:</label>
                        <div class="col-md-offset-4">
                            <input id="newCategory" name="newCategory" type="text" placeholder="" class="form-control input-md">
                        </div>
                    </div>
                    <!-- Get Answer1 -->
                    <div class="form-group col-md-12">
                        <label class="col-md-4 control-label" for="formAnswer">Answer: </label>
                        <div class="col-sm-pull-8">
                            <div class="input-group">
                                <input id="formAnswer" name="formAnswer" class="form-control" type="text" maxlength="255">
                                <span class="input-group-addon">
                                    <input type="checkbox" name="formC" class="checkbox_check" value="1">
                                </span>
                            </div>
                        </div>
                    </div>
                    <!-- Get Answer2 -->
                    <div class="form-group col-md-12">
                        <label class="col-md-4 control-label" for="formAnswer">Answer: </label>
                        <div class="col-sm-pull-8">
                            <div class="input-group">
                                <input id="formAnswer" name="formAnswer" class="form-control" type="text" maxlength="255">
                                <span class="input-group-addon">
                                    <input type="checkbox" name="formC" class="checkbox_check" value="1">
                                </span>
                            </div>
                        </div>
                    </div>
                    <!-- More Answers -->
                    <div id="AddHere"></div>
                    <!-- File Button -->
                    <div class="form-group col-md-12">
                        <label class="col-md-4 control-label" for="filebutton">Upload Image:</label>
                        <div class="col-sm-pull-8">
                            <input id="filebutton" name="formFile" class="input-file" type="file" style="vertical-align:top;">
                        </div>
                    </div>
                    <!-- Submit Button -->
                    <div class="form-group col-md-12">
                        <label class="col-md-4 control-label" for="submitButton"></label>
                        <div class="col-md-8">
                            <button class="btn btn-info" onclick="AddAnswer()"><span class="glyphicon glyphicon-plus"></span> Add More Answers</button>
                            <button id="SubmitButton" name="SubmitButton" class="btn btn-success" onclick="SendQuestion()">Submit</button>
                        </div>
                    </div>
                </fieldset>
            </div>  <!--Modal Body-->

        </div> <!--Modal Content-->
    </div> <!--Modal Dialog-->
</div>

<!--************************List Questions*****************************-->
<br />
<ul class="Test" style="list-style-type:none">
    @Html.Raw(ListHelp.EditListString())
</ul>

@section scripts{
    <script>
        function AddAnswer() {
            $("<div class='form-group col-md-12'><label class='col-md-4 control-label' for='formAnswer'>Answer: </label><div class='col-md-8'><div class='input-group'><input id='formAnswer' name='formAnswer' class='form-control' type='text' maxlength='255'><span class='input-group-addon'><input type='checkbox' name='formC' class='checkbox_check' value='1'></span></div></div></div>").insertBefore("#AddHere");
        }

        function SendQuestion() {
            var formData = new FormData();
            formData.append("file", document.getElementById("filebutton").files[0]);
            var xhr = new XMLHttpRequest();
            xhr.open("POST", "/Home/UploadImage", true);
            xhr.addEventListener("load", function (evt) { UploadComplete(evt, xhr.responseText); }, false);
            xhr.addEventListener("error", function (evt) { UploadFailed(evt, xhr.responseText); }, false);
            xhr.send(formData);
        }

        function UploadComplete(evt, name) {
            if (evt.target.status == 200) {
                var Answers = document.getElementsByName("formAnswer");
                var Corrects = document.getElementsByName("formC");

                var JSONObj = {};
                JSONObj.Question = document.getElementsByName("formQuestion")[0].value;
                JSONObj.QuestionID = "new";
                JSONObj.Pic = name;
                JSONObj.Catagory = document.getElementsByName("newCategory")[0].value;
                JSONObj.CategoryDropDown = document.getElementsByName("formCategory")[0].value;
                JSONObj.Answers = [];
                JSONObj.Corrects = [];

                for (var i = 0; i < Answers.length; i++) {
                    JSONObj.Answers.push(Answers[i].value);
                    if (Corrects[i].checked) {
                        JSONObj.Corrects.push(1);
                    } else {
                        JSONObj.Corrects.push(0);
                    }
                }

                $.ajax({
                    url: "@(ViewBag.ResultsURL)",
                    type: "POST",
                    contentType: "application/json",
                    dataType: "json",
                    data: JSON.stringify(JSONObj),
                    success: function (data) {
                        if (data != null) {
                            window.location.href = '@Url.Action("Edit", "Home")';
                        } else {
                            alert("ERROR:Data not submitted");
                        }
                    }
                });
            }
            else
            {
                alert("Error Uploading File" + name);
            }
        }

        function UploadFailed(evt, name) {
            alert("There was an error attempting to upload the file." + name);

        }

    </script>
}

L2Test/L2Test/Views/Home/Home.cshtml
@{
    ViewBag.Title = "L2 Test";
}

<div class="SubmitFloat">
    <center> </center>
</div>

<!--
 _____           _           _     _         _      _____   _____         _
|  __ \         | |         | |   | |       | |    / __  \ |_   _|       | |
| |  \/ ___   __| | __ _  __| | __| |_   _  | |    `' / /'   | | ___  ___| |_
| | __ / _ \ / _` |/ _` |/ _` |/ _` | | | | | |      / /     | |/ _ \/ __| __|
| |_\ \ (_) | (_| | (_| | (_| | (_| | |_| | | |____./ /___   | |  __/\__ \ |_
 \____/\___/ \__,_|\__,_|\__,_|\__,_|\__, | \_____/\_____/   \_/\___||___/\__|
                                      __/ |
                                     |___/
-->
<br />
<article id="TestRequirements">
        @Html.Raw(ViewBag.HomePageText)
</article>
<br />
<br />
<br />
<form action="" method="post" enctype="multipart/form-data" class="form-horizontal">
    <fieldset>
        <!-- Text input-->
        <div class="form-group">
            <label class="col-md-4 control-label" for="formTechID">Enter Your Test ID</label>
            <div class="col-md-4">
                <input id="formTechID" name="formTechID" type="text" placeholder="" class="form-control input-md" required="">
                <span class="help-block" style="color:red;font-weight:700">@ViewBag.Error</span>
            </div>
        </div>

        <!-- Button -->
        <div class="form-group">
            <label class="col-md-4 control-label" for="submitButton"></label>
            <div class="col-md-4">
                <button id="submitButton" name="submitButton" class="btn btn-success">Take L2 Test</button>
            </div>
        </div>

    </fieldset>
</form>

L2Test/L2Test/Views/Home/ReportCards.cshtml

@{
    ViewBag.Title = "ReportCards";
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.ResultsURL = Url.Action("ReportCards", "Archive", routeValues: null, protocol: Request.Url.Scheme);
}

<div class="SubmitFloat">
    <center></center>
</div>

<!--
 _____           _           _     _         _      _____   _____         _
|  __ \         | |         | |   | |       | |    / __  \ |_   _|       | |
| |  \/ ___   __| | __ _  __| | __| |_   _  | |    `' / /'   | | ___  ___| |_
| | __ / _ \ / _` |/ _` |/ _` |/ _` | | | | | |      / /     | |/ _ \/ __| __|
| |_\ \ (_) | (_| | (_| | (_| | (_| | |_| | | |____./ /___   | |  __/\__ \ |_
 \____/\___/ \__,_|\__,_|\__,_|\__,_|\__, | \_____/\_____/   \_/\___||___/\__|
                                      __/ |
                                     |___/
-->

<div class="row">
    <div class="col-xs-6 col-sm-6 col-lg-6">
        <center>
            <h3>Graded Tests</h3>
            <ul class="Test">
                @Html.Raw(ViewBag.GradedResults)
            </ul>
        </center>
    </div>
    <div class="col-xs-6 col-sm-6 col-lg-6">
        <center>
            <h3>Not Graded Archive</h3>
            <ul class="Test">
                @Html.Raw(ViewBag.ArchiveResults)
            </ul>
        </center>
    </div>
</div>
<form action="/L2Test/Complete/Archive/ReportCards" method="POST" id="formSubmit">
    <div id="data"></div><input type="hidden" name="filepath" value="">
</form>
    @section scripts{
        <script>
            $('.getTest').click(function () {
                var filepath = $(this).attr('id');
                var data = document.getElementById('data');
                data.innerHTML = '<input type="hidden" name="filepath" value="' + filepath + '">'
                $('#formSubmit').submit();
            });
        </script>
    }